drop table #cx_bldg;
CREATE TABLE #cx_bldg ( c varchar(8), t varchar(100) );
INSERT INTO #cx_bldg VALUES('ANDT','Townhouse - Andover');
INSERT INTO #cx_bldg VALUES('ASH','Ash Centre');
INSERT INTO #cx_bldg VALUES('BOXT','Townhouse - Boxford');
INSERT INTO #cx_bldg VALUES('CHET','Townhouse - Chelmsford');
INSERT INTO #cx_bldg VALUES('DEGE','Deegan Hall East');
INSERT INTO #cx_bldg VALUES('DEGN','Deegan Hall');
INSERT INTO #cx_bldg VALUES('DEGW','Deegan Hall West');
INSERT INTO #cx_bldg VALUES('DRAT','Townhouse - Dracut');
INSERT INTO #cx_bldg VALUES('EHS','Hennigan Ctr (Haver. St)');
INSERT INTO #cx_bldg VALUES('GEOT','Townhouse - Georgetown');
INSERT INTO #cx_bldg VALUES('HAVT','Townhouse - Haverhill');
INSERT INTO #cx_bldg VALUES('LAWT','Townhouse - Lawrence');
INSERT INTO #cx_bldg VALUES('LOWT','Townhouse - Lowell');
INSERT INTO #cx_bldg VALUES('METT','Townhouse - Methuen');
INSERT INTO #cx_bldg VALUES('MON','Monican Centre');
INSERT INTO #cx_bldg VALUES('NANT','Townhouse - North Andover');
INSERT INTO #cx_bldg VALUES('NEW1','South Res Village 1');
INSERT INTO #cx_bldg VALUES('NEW2','South Res Village 2');
INSERT INTO #cx_bldg VALUES('NEW3','South Res Village 3');
INSERT INTO #cx_bldg VALUES('NEW4','South Res Village 4');
INSERT INTO #cx_bldg VALUES('NEW5','South Res Village 5');
INSERT INTO #cx_bldg VALUES('NRT1','North Res Village 7');
INSERT INTO #cx_bldg VALUES('NRT2','North Res Village 6');
INSERT INTO #cx_bldg VALUES('NRV6','North Res Village 6');
INSERT INTO #cx_bldg VALUES('NRV7','North Res Village 7');
INSERT INTO #cx_bldg VALUES('OBRN','O''Brien Hall');
INSERT INTO #cx_bldg VALUES('PELT','Townhouse - Pelham');
INSERT INTO #cx_bldg VALUES('RC1','Royal Crest 1');
INSERT INTO #cx_bldg VALUES('RC10','Royal Crest 10');
INSERT INTO #cx_bldg VALUES('RC11','Royal Crest 11');
INSERT INTO #cx_bldg VALUES('RC12','Royal Crest 12');
INSERT INTO #cx_bldg VALUES('RC13','Royal Crest 13');
INSERT INTO #cx_bldg VALUES('RC14','Royal Crest 14');
INSERT INTO #cx_bldg VALUES('RC18','Royal Crest 18');
INSERT INTO #cx_bldg VALUES('RC19','Royal Crest 19');
INSERT INTO #cx_bldg VALUES('RC2','Royal Crest 2');
INSERT INTO #cx_bldg VALUES('RC20','Royal Crest 20');
INSERT INTO #cx_bldg VALUES('RC21','Royal Crest 21');
INSERT INTO #cx_bldg VALUES('RC22','Royal Crest 22');
INSERT INTO #cx_bldg VALUES('RC23','Royal Crest 23');
INSERT INTO #cx_bldg VALUES('RC24','Royal Crest 24');
INSERT INTO #cx_bldg VALUES('RC25','Royal Crest 25');
INSERT INTO #cx_bldg VALUES('RC26','Royal Crest 26');
INSERT INTO #cx_bldg VALUES('RC27','Royal Crest 27');
INSERT INTO #cx_bldg VALUES('RC28','Royal Crest 28');
INSERT INTO #cx_bldg VALUES('RC29','Royal Crest 29');
INSERT INTO #cx_bldg VALUES('RC3','Royal Crest 3');
INSERT INTO #cx_bldg VALUES('RC30','Royal Crest 30');
INSERT INTO #cx_bldg VALUES('RC31','Royal Crest 31');
INSERT INTO #cx_bldg VALUES('RC32','Royal Crest 32');
INSERT INTO #cx_bldg VALUES('RC33','Royal Crest 33');
INSERT INTO #cx_bldg VALUES('RC34','Royal Crest 34');
INSERT INTO #cx_bldg VALUES('RC35','Royal Crest 35');
INSERT INTO #cx_bldg VALUES('RC36','Royal Crest 36');
INSERT INTO #cx_bldg VALUES('RC37','Royal Crest 37');
INSERT INTO #cx_bldg VALUES('RC38','Royal Crest 38');
INSERT INTO #cx_bldg VALUES('RC39','Royal Crest 39');
INSERT INTO #cx_bldg VALUES('RC4','Royal Crest 4');
INSERT INTO #cx_bldg VALUES('RC40','Royal Crest 40');
INSERT INTO #cx_bldg VALUES('RC41','Royal Crest 41');
INSERT INTO #cx_bldg VALUES('RC42','Royal Crest 42');
INSERT INTO #cx_bldg VALUES('RC43','Royal Crest 43');
INSERT INTO #cx_bldg VALUES('RC44','Royal Crest 44');
INSERT INTO #cx_bldg VALUES('RC46','Royal Crest 46');
INSERT INTO #cx_bldg VALUES('RC47','Royal Crest 47');
INSERT INTO #cx_bldg VALUES('RC48','Royal Crest 48');
INSERT INTO #cx_bldg VALUES('RC49','Royal Crest 49');
INSERT INTO #cx_bldg VALUES('RC5','Royal Crest 5');
INSERT INTO #cx_bldg VALUES('RC6','Royal Crest 6');
INSERT INTO #cx_bldg VALUES('RC7','Royal Crest 7');
INSERT INTO #cx_bldg VALUES('RC8','Royal Crest 8');
INSERT INTO #cx_bldg VALUES('RC9','Royal Crest 9');
INSERT INTO #cx_bldg VALUES('RCRE','Royal Crest Apartments');
INSERT INTO #cx_bldg VALUES('SALT','Townhouse - Salem');
INSERT INTO #cx_bldg VALUES('SANT','O''Brien Hall');
INSERT INTO #cx_bldg VALUES('SRV1','South Res Village 1');
INSERT INTO #cx_bldg VALUES('SRV2','South Res Village 2');
INSERT INTO #cx_bldg VALUES('SRV3','South Res Village 3');
INSERT INTO #cx_bldg VALUES('SRV4','South Res Village 4');
INSERT INTO #cx_bldg VALUES('SRV5','South Res Village 5');
INSERT INTO #cx_bldg VALUES('STA','St. Ann Apartments');
INSERT INTO #cx_bldg VALUES('STFR','St. Francis');
INSERT INTO #cx_bldg VALUES('STT','St. Thomas Apartments');
INSERT INTO #cx_bldg VALUES('TBA','To Be Announced');
INSERT INTO #cx_bldg VALUES('TEWT','Townhouse - Tewksbury');
INSERT INTO #cx_bldg VALUES('TYNT','Townhouse');

SELECT c CX_NOT_J1, t descr
FROM #cx_bldg
WHERE c NOT IN (select distinct bldg_cde from building_master);

SELECT bldg_cde J1_NOT_CX, building_desc
FROM building_master
WHERE bldg_cde NOT IN (select c from #cx_bldg);

